version: '3'

services:

  application:
    build:
      context: ./application
      dockerfile: development.Dockerfile
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: hunter2
      MYSQL_ADDRESS: database:3306
      MYSQL_DATABASE: docker_0111
    volumes:
      - ./application:/go/src/github.com/Financial-Times/docker-0111-application/
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: hunter2
    volumes:
      - ./database:/docker-entrypoint-initdb.d